#!/usr/bin/env bash 

TARGET="$(hostname)"

while getopts "t:" opt; do
  case "$opt" in
    t) TARGET="$OPTARG" ;;
    *) echo "Usage: $0 [-t target] [nixos-rebuild-args...]"; exit 1 ;;
  esac
done

shift $((OPTIND - 1))

export NH_FILE=./nixos.nix
export NH_ATTRP="${TARGET}"

nh os "$@"
