# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/06b1dbb3-ed19-43f0-992c-ba12820a2f4c";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/CD19-4DFD";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/bdedf832-219d-41d4-8701-150d6a4ff0dd"; }
    { device = "/swapfile"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
